# Generated by Django 5.0.4 on 2024-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfps'),
        ),
    ]
