# Generated by Django 5.0.4 on 2024-05-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_user_chat_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
